### PR TITLE
Use es_PE as language; add overrides to es_PE messages file

### PR DESCRIPTION
**Pull request by brandones**

### CODE REVIEW

**Review by MiguelAHPpih — APPROVED** [review]
Looks good. 
One thing, this messages_es_PE properties file will overwrite any message code that is used in the pihemr spanish properties file, right?

**Comment by brandones** [comment]
Any message code in messages_es_PE will override message codes in messages_es, yeah.

**Comment by brandones** [comment]
Wait, big problem. @mseaton @mogoodrich Angular doesn't recognize `es_PE` as a valid locale:

Screenshot from 2021-11-08 15-14-17

Looks like Angular expects locales to be dash-separated, e.g. `es-PE`. I'm looking into whether we can fix that in uiframework.

**Review by mseaton — APPROVED** [review]

**Comment by mogoodrich** [comment]
@brandones  I remember having to deal with this discrepency previously but don't remember off the top of my head where, unfortunately... but there might be some hacky code in place somewhere to replace the underscore with a hyphen or vice versa.

**Comment by mogoodrich** [comment]
So I didn't find where I was facing the above problem, but I did discover that the Message Controller that serves up the translations (for Angular Translate, which I believe is what we are still using), only currently supports languages, not countries, so that would likely need to be fixed as well:

https://issues.openmrs.org/browse/UICM-80

**Comment by mogoodrich** [comment]
So it might be as simple as reformatting the locale from Java format to Angular format (ie replace "_" with "-") when populating the locale in the model for use by JavaScript?  (But we'd still need to update the MessageController to support countries)

**Comment by brandones** [comment]
Thanks @mogoodrich ! Tested it and it works great. https://github.com/PIH/openmrs-module-pihcore/pull/321

**Review by mogoodrich — APPROVED** [review]
It think this works for me, assuming the assumption I referenced in my comment (we don't yet need to customize the Visit note translations differently between Mexico and Peru).

**Pull request merged**
