### PR TITLE
Remove invalid lab concept GP

### PR DESCRIPTION
**Pull request by brandones**
Screenshot from 2020-11-09 16-24-39

### CODE REVIEW

**Review by mogoodrich — APPROVED** [review]
Perfect!  Yes, we can just leave it empty with this comment for now, thanks...

**Comment by aastupilloses** [comment]
So, this change removes temporarily the laboratory location UUID, right? Because we don't have a "laboratory" location yet...

**Comment by brandones** [comment]
Yeah, I had actually used the GP totally incorrectly—it's supposed to be the UUID of a concept like PIH:12868, not the UUID of an actual location.

**Comment by aastupilloses** [comment]
@brandones Oh, that makes sense! It's OK for me.

**Pull request merged**
