### PR TITLE
PER-387 Enable Reports module

### PR DESCRIPTION
**Pull request by brandones**
https://pihemr.atlassian.net/browse/PER-387

Screenshot from 2021-01-20 15-15-39

### CODE REVIEW

**Review by mogoodrich — COMMENTED** [review]
@brandones  I *think* just doing "dataExports" will do the trick, and it should just enable the data exports associated with components that are enabled on the server.

iirc, "allDataExports" is used just for the Mirebalais Reporting server (which is just a reporting server and doesn't have any other components enabled turned on, so just using "dataExports" wasn't actually doing anything there)

Anyway, you can try that out and ping me and I can research more tomorrow if need be...

**Comment by brandones** [comment]
I see; so
Screenshot from 2021-01-21 09-20-21
is actually the correct list of reports for us to work from?

**Comment by mogoodrich** [comment]
So @brandones  this should, theortically, be all the reports supported by the components that are currently turned on on the SES server.  You can compare the two lists to see if there's something in the larger list that you'd expect to see, but, for example, I wouldn't expect the "ED Triage" report or the "Pathology" report to show up unless those features are enabled. Nor the NCD reports unless the NCD program is enabled, etc...

**Comment by brandones** [comment]
@mogoodrich Right, yes. The only one I'm expecting to see but not seeing is the COVID-19 forms. Should we plan to handle that in a separate PR?

**Comment by mogoodrich** [comment]
to be clear @brandones , you mean the COVID-19 forms are enabled on the server, but we aren't seeing the report listed?
Yeah, just made that 2-point ticket and put it in this sprint and we can figure it out.

**Comment by brandones** [comment]
Filed https://pihemr.atlassian.net/browse/PER-389 . 

Okay, this is just pending review by @aastupilloses  or @MiguelAHPpih .

**Comment by brandones** [comment]
Ping, @MiguelAHPpih

**Comment by aastupilloses** [comment]
Hi, Brandon. So, this feature is going to be enabled for us, but you are going to check why COVID-19 forms are not being listed in the reports list, right? It sounds good to me. We can start enabling this and then adding the referred forms to the list when a fix for that issue would be available.

**Comment by brandones** [comment]
@aastupilloses Yep! @mogoodrich already made the [fix](expand the conversation to more people at more sites, get people's feedback) so hopefully once this is in CI the COVID report will appear.

**Pull request merged**
