### PR TITLE
Covid Program configuration

### PR DESCRIPTION
**Pull request by MiguelAHPpih**

### CODE REVIEW

**Comment by brandones** [comment]
Looks like it has conflicts that need to be resolved

**Comment by MiguelAHPpih** [comment]
What exactly is the conflict? I renamed the covid19intakeform to covid19, just like we saw a couple of hours ago

**Review by mogoodrich — APPROVED** [review]
LGTM (if your intent is to enable the full COVID functionality)

**Comment by brandones** [comment]
screenshot--2021-01-25--145912
:man_shrugging:

**Pull request merged**
