### PR TITLE
Add markPatientDead component

### PR DESCRIPTION
**Pull request by brandones**
I propose using this feature, instead of having "Dead" and "Dead date" as a [question on every intake from](https://docs.google.com/spreadsheets/d/1xL1gax08c_3_HF7nnri124p1A_VKX6_E6hlfkhOWhDE/edit#gid=0&range=153:154).

screenshot--2020-12-11--101044
Screenshot from 2020-12-11 10-11-33

### CODE REVIEW

**Comment by brandones** [comment]
@aastupilloses , @MiguelAHPpih ?

**Comment by aastupilloses** [comment]
Hi, Brandon. It looks good to me. Just one question: is that death date only informative? Does it change something in the programs workflows or the system workflow after ticking that checkbox?

**Comment by brandones** [comment]
Hi @aastupilloses , I don't believe that the functionality is integrated into program workflows (such as by automatically marking the patient as terminating the program with outcome "died"), though that would be cool. @lnball or @mogoodrich can probably speak more to that though.

**Comment by lnball** [comment]
Unfortunately it does not change the program outcome, but that would be a VERY useful feature.

**Pull request merged**
